image: node:14

pipelines:
    branches:
        main:
            - step:
                  script:
                      - echo "maincode/" >> .gitignore
                      - git add .gitignore
                      - git commit -m "Add .gitignore"
                      - git push git@github.com:javishome/javis_cam_ai.git:$BITBUCKET_BRANCH