image: node:14

pipelines:
    branches:
        main:
            - step:
                  script:
                      - rm -rf maincode
                      - git add .
                      - git commit -m "Update maincode"
                      - git push git@github.com:javishome/javis_cam_ai.git