image: node:14

pipelines:
    branches:
        main:
            - step:
                  script:
                      - ls 
                      - rm -rf ./main_code
                      - git add .
                      - ls
                      - git commit -m "Update maincode"
                      - git push --all git@github.com:javishome/javis_cam_ai.git