write_person:
  name: Log person
  description: Log person
  fields:
    payload:
      name: Payload
      description: Payload
      required: true
      selector:
        text:

push_to_qcd:
  name: push all data to qcd
  description: push all data to qcd
  fields:
    secret_key:
      name: Secret key
      description:  Secret key
      required: true
      selector:
        text: