name: Create Release manually

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "nhập phiên bản HA cần build"
        required: true
        default: "2024_12_4"
        type: string # Định nghĩa rõ kiểu dữ liệu đầu vào

# Thêm quyền write để GITHUB_TOKEN có thể xóa và ghi đè release/tag cũ
permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from manifest.json
        id: get_version
        run: echo "VERSION=$(jq -r '.version' build/${{ github.event.inputs.set_release }}/manifest.json)" >> $GITHUB_ENV

      - name: Delete old release and tag (if exists)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Tự động xóa release và tag bị trùng dựa trên tham số đầu vào
        run: gh release delete "v${{ github.event.inputs.set_release }}_${{ env.VERSION }}" --cleanup-tag -y || true

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/build/${{ github.event.inputs.set_release }}
          zip -r javis_hanet.zip ./

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.event.inputs.set_release }}_${{ env.VERSION }}"
          release_name: "Release v${{ github.event.inputs.set_release }}_${{ env.VERSION }}"
          body: "### Changelog\n\n- Cập nhật v${{ github.event.inputs.set_release }}_${{ env.VERSION }}."
          draft: false
          prerelease: false
          files: build/${{ github.event.inputs.set_release }}/javis_hanet.zip # Upload trực tiếp file zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}